"""In-chat @neko wallet tracking: parser, reply text, and subscription guard.

Mirrors chatbuy.py / chatwallet.py's shape — pure parse + text here, the caller
owns the Telegram API. A TRACKED wallet is just an on-chain Sui address; it does
NOT need a bot/DB row (it may be any trader we want to follow). The subscriber
is identified by tg user id, capped at MAX_TRACKS per user.

Alerts are generated by the background WalletTracker (tracker.py) from the live
SuiPump TokensPurchased/TokensSold stream, filtered to these subscriptions.
"""
from __future__ import annotations

import os
import re

from chatbuy import esc  # shared HTML escaping

MAX_TRACKS = 8

# A full Sui address must be exactly 0x + 64 hex chars (Sui uses one canonical
# address format; EVM/0x12… short forms are rejected).
_ADDR_RE = re.compile(r"(?i)^0x[0-9a-f]{64}$")

# "@<bot> track 0x…" | "@<bot> follow 0x…" | "@<bot> watch 0x…"
_TRACK_RE = re.compile(
    r"(?i)^\s*@([A-Za-z0-9_]{3,64})\b\s*(?:(?:track|follow|watch|monitor)\s+)(0x[0-9a-fA-F]{1,})$"
)
# "@<bot> untrack|remove|unfollow|unwatch 0x…" | "@<bot> stop tracking 0x…"
_UNTRACK_RE = re.compile(
    r"(?i)^\s*@([A-Za-z0-9_]{3,64})\b\s*(?:(?:untrack|remove|unfollow|unwatch)|stop\s+track(?:ing)?)\s+(0x[0-9a-fA-F]{1,})$"
)
# "@<bot> my tracks" | "@<bot> track list" | "@<bot> tracks"
_LIST_RE = re.compile(
    r"(?i)^\s*@([A-Za-z0-9_]{3,64})\b\s*(?:(?:my\s+)?tracks?|track\s+list|list\s+tracks?)$"
)


def chat_usernames_from_env() -> list[str]:
    """Bot usernames that trigger in-chat tracking (NEKO_CHAT_USERNAMES)."""
    raw = os.getenv("NEKO_CHAT_USERNAMES", "neko_tradesbot")
    return [u.strip().lstrip("@") for u in raw.split(",") if u.strip()]


def parse_chat_track(text: str, usernames: list[str]) -> dict | None:
    """Parse an in-chat @mention tracking message.

    Returns:
        {"op": "track",  "wallet": str, "mention": str}     — subscribe
        {"op": "untrack","wallet": str, "mention": str}     — unsubscribe
        {"op": "list",   "mention": str}                    — show active
        {"op": "track"/"untrack", "wallet": str, "mention": str,
         "error": str}                                      — malformed wallet
        None — not a tracking mention (caller falls through).
    """
    if not text:
        return None
    names = {u.lower().lstrip("@") for u in usernames}

    m = _LIST_RE.match(text)
    if m and m.group(1).lower() in names:
        return {"op": "list", "mention": m.group(1)}

    m = _TRACK_RE.match(text)
    if m:
        mention, addr = m.group(1), m.group(2)
        if mention.lower() not in names:
            return None
        if not _full_address(addr):
            return {"op": "track", "wallet": addr, "mention": mention,
                    "error": "I need a full Sui address (0x + 64 hex chars)."}
        return {"op": "track", "wallet": addr.lower(), "mention": mention}

    m = _UNTRACK_RE.match(text)
    if m:
        mention, addr = m.group(1), m.group(2)
        if mention.lower() not in names:
            return None
        if not _full_address(addr):
            return {"op": "untrack", "wallet": addr.lower(), "mention": mention,
                    "error": "I need a full Sui address (0x + 64 hex chars)."}
        return {"op": "untrack", "wallet": addr.lower(), "mention": mention}

    return None


def _full_address(addr: str) -> bool:
    return bool(_ADDR_RE.match(addr))


def short_wallet(addr: str) -> str:
    """0x<64> → 0xabc…12f4 for compact alert bodies."""
    a = addr.lower()
    return f"{a[:7]}…{a[-4:]}" if len(a) > 12 else a


def tracked_reply(username: str = "", count: int = 1, max_tracks: int = MAX_TRACKS,
                  mention: str = "") -> str:
    name = esc(username or "trader")
    mention = esc(mention or "neko_tradesbot")
    return (f"🐾 Neko is keeping an eye on this wallet. ({count}/{max_tracks})\n\n"
            f"⚡ Trade with @{mention}")


def limit_reply(username: str = "", max_tracks: int = MAX_TRACKS) -> str:
    name = esc(username or "trader")
    return (f"⚠️ @{name}, you're at the <b>{max_tracks}-wallet</b> limit.\n"
            f"Untrack one first: <code>@neko untrack 0x…</code>")


def untracked_reply(username: str = "", wallet: str = "") -> str:
    name = esc(username or "trader")
    return f"🐾 @{name}, stopped tracking <code>{esc(short_wallet(wallet))}</code>."


def not_tracked_reply(username: str = "", wallet: str = "") -> str:
    name = esc(username or "trader")
    return f"🐾 @{name}, <code>{esc(short_wallet(wallet))}</code> wasn't being tracked."


def empty_reply(username: str = "") -> str:
    name = esc(username or "trader")
    return (f"🐾 @{name}, you're not tracking any wallet yet.\n"
            f"Try: <code>@neko track 0x…</code>")


def list_reply(rows: list[dict], username: str = "", max_tracks: int = MAX_TRACKS) -> str:
    name = esc(username or "trader")
    if not rows:
        return empty_reply(username)
    lines = [f"🐾 @{name}, tracking {len(rows)}/{max_tracks} wallet(s):"]
    for i, r in enumerate(rows, 1):
        buys = r.get("buys", 3)
        scope = "buys+sells" if buys == 3 else ("buys" if buys == 1 else "sells")
        lines.append(f"  {i}. <code>{esc(r['wallet'])}</code> · {scope} · "
                     f"min {r.get('min_sui', 1.0):g} SUI")
    lines.append("Untrack: <code>@neko untrack 0x…</code>")
    return "\n".join(lines)